site:
  author:
  name: Yuva Peavler
  email: "yuva.peavler@gmail.com"
title: Yuva's Blog
author:
  name: ypeavler
  email: yuva.peavler@gmail.com
description: >
  Write something thoughtful here. 

minima:
  hide_site_feed_link: true
  skin: dark
  date_format: "%b %-d, %Y"
  show_excerpts: true

# Build settings
baseurl: /blog
remote_theme: jekyll/minima

sass:
  quiet_deps: true
  silence_deprecations: [import]